<a href="https://colab.research.google.com/github/JEN12H/PYTORCH/blob/main/AUTOGRAD_PYTORCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x = torch.tensor(3.0,requires_grad=True) # FOR SIMPLIFIED DERIVATIVE OF x

In [ ]:
y = x ** 2
x

tensor(3., requires_grad=True)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
import math
def dz_dx(x):
  return 2*x*math.cos(x**2)

In [ ]:
dz_dx(3)

-5.466781571308061

In [ ]:
x = torch.tensor(3.0,requires_grad=True)

In [ ]:
y = x **2
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
z = torch.sin(y)
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-5.4668)

In [ ]:
# NEUEAL NETWORK IN PYTORCH
x = torch.tensor(6.7)
y = torch.tensor(0.0) # ACTUAL TARGET
w = torch.tensor(1.0)
b = torch.tensor(0.0)

In [ ]:
def binary_crossentropy_loss(prediction,target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction,epsilon,1-epsilon)
  return -(target * torch.log(prediction)+ (1-target)*torch.log(1-prediction))

In [ ]:
# FORWARD PASS
z = w *x + b
y_pred = torch.sigmoid(z)
loss = binary_crossentropy_loss(y_pred,y)

In [ ]:
#Derivatives:
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred)) # dL/dy_pred
dy_pred_dz = y_pred * (1-y_pred) #dy_pred/dz
dz_dw = x #dz//dw
dz_db = 1 #dz/db
dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [ ]:
print(f"Manual Gradient Loss w.r.t weight (dw):{dL_dw}")
print(f"Manual Gradient Loss w.r.t bias (dw):{dL_db}")

Manual Gradient Loss w.r.t weight (dw):6.691762447357178
Manual Gradient Loss w.r.t bias (dw):0.998770534992218


# NOW USING AUTOGRAD

In [ ]:
x = torch.tensor(6.7)
y = torch.tensor(0.0)
w = torch.tensor(1.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)

In [ ]:
w

tensor(1., requires_grad=True)

In [ ]:
z = w*x + b

In [ ]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [ ]:
loss = binary_crossentropy_loss(y_pred,y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()

In [ ]:
w.grad

tensor(6.6918)

In [ ]:
b.grad

tensor(0.9988)

In [ ]:
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
y = (x**2).mean()

In [ ]:
y.backward()

In [ ]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [ ]:
#clearing gradients it is important to clear them otherwise it will get accumulated
x.grad.zero_()

tensor([0., 0., 0.])

In [ ]:
x.requires_grad_(False)

tensor([1., 2., 3.])

In [ ]:
z = x.detach()
z

tensor([1., 2., 3.])

In [ ]:
y = x ** 2

In [ ]:
y1 = x ** 2

In [ ]:
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
with torch.no_grad():
  y = x **2

In [ ]:
y

tensor([1., 4., 9.])

In [ ]:
#y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn