<a href="https://colab.research.google.com/github/JEN12H/PYTORCH/blob/main/NN_MODULE_PYTORCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network = nn.Sequential(
     nn.Linear(num_features,3),
     nn.ReLU(),
     nn.Linear(3,1),
     nn.Sigmoid()
     )

  def forward(self,features):
   out = self.network(features)

   return out

In [ ]:
features = torch.rand(10,5) # CREATING DATASET

In [ ]:
model = Model(features.shape[1])

In [ ]:
model(features)

tensor([[0.5821],
        [0.5856],
        [0.5784],
        [0.5812],
        [0.5687],
        [0.5885],
        [0.5698],
        [0.5879],
        [0.5936],
        [0.5821]], grad_fn=<SigmoidBackward0>)

In [ ]:
model.linear1.weight

Parameter containing:
tensor([[-0.1070, -0.1424,  0.2423, -0.0107,  0.3880],
        [-0.2244,  0.3321, -0.4430,  0.2686, -0.4215],
        [-0.0256, -0.1448, -0.0552,  0.2013, -0.4059]], requires_grad=True)

In [ ]:
model.linear2.bias

Parameter containing:
tensor([-0.0164], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00