<a href="https://colab.research.google.com/github/JEN12H/PYTORCH/blob/main/PYTORCH_PIPELINE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("/content/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [5]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

In [6]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
y_train

473    B
256    M
71     B
404    B
177    M
      ..
561    B
363    B
383    B
331    B
113    B
Name: diagnosis, Length: 455, dtype: object

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
y_train

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,

#NUMPY ARRAYS TO TENSORS

In [10]:
X_train_tensor = torch.from_numpy(X_train_scaled)
X_test_tensor = torch.from_numpy(X_test_scaled)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [11]:
X_train_tensor.shape

torch.Size([455, 30])

In [22]:
from torch.utils.data import Dataset, DataLoader
class CustomDataset(Dataset):
  def __init__(self,features,labels):
     self.features = features
     self.labels = labels
  def __len__(self):
    return len(self.features)
  def __getitem__(self,index):
    return self.features[index],self.labels[index]

In [23]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [25]:
train_loader = DataLoader(train_dataset,batch_size = 32,shuffle = True)
test_loader = DataLoader(test_dataset,batch_size = 32,shuffle=True)

# BUILDING NEURAL NETWORK

In [26]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()
  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out




In [27]:
learning_rate = 0.1
epochs = 25

In [28]:
loss_function = nn.BCELoss()

In [29]:
#CREATING MODEL
model = MySimpleNN(X_train_tensor.shape[1])
#DEFINING OPTIMIZER
optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)
for epoch in range(epochs):
  # FORWARD PASS
  X_train_tensor = X_train_tensor.type(torch.float32)
  y_pred = model(X_train_tensor)
  print(y_pred)
  #calculating loss
  loss = loss_function(y_pred,y_train_tensor.type(torch.float32).view(-1,1))
  # RESETTING GRADIENTS
  optimizer.zero_grad()
  # BACKWARD PASS
  loss.backward()
  # UPDATING PARAMETERS
  optimizer.step()


  # print  loss in each epoch
  print(f'EPOCHS:{epoch + 1},loss :{loss.item()}')



tensor([[0.7242],
        [0.5796],
        [0.1230],
        [0.4215],
        [0.4900],
        [0.6253],
        [0.5750],
        [0.1788],
        [0.4511],
        [0.4598],
        [0.5626],
        [0.4888],
        [0.5311],
        [0.6358],
        [0.4533],
        [0.3799],
        [0.2693],
        [0.4374],
        [0.4083],
        [0.4999],
        [0.5227],
        [0.6076],
        [0.4480],
        [0.5416],
        [0.3650],
        [0.4604],
        [0.4281],
        [0.4449],
        [0.4987],
        [0.4240],
        [0.3873],
        [0.4353],
        [0.5394],
        [0.5131],
        [0.4567],
        [0.4987],
        [0.3551],
        [0.5416],
        [0.4533],
        [0.5235],
        [0.3703],
        [0.5062],
        [0.4504],
        [0.5224],
        [0.6739],
        [0.3033],
        [0.5448],
        [0.4236],
        [0.5281],
        [0.4907],
        [0.7475],
        [0.5279],
        [0.6408],
        [0.4554],
        [0.5136],
        [0

In [30]:
model.linear.bias

Parameter containing:
tensor([-0.2416], requires_grad=True)

In [31]:
model.linear.weight

Parameter containing:
tensor([[ 0.1974,  0.2309,  0.2161,  0.2095,  0.1726, -0.0075,  0.2181,  0.3711,
          0.1286, -0.2007,  0.0586,  0.0904,  0.2729,  0.0438, -0.1579,  0.0450,
         -0.1225,  0.1792, -0.0286, -0.1020,  0.4189,  0.2441,  0.1563,  0.2970,
          0.2492,  0.1408,  0.2578,  0.1100,  0.0243,  0.2502]],
       requires_grad=True)

In [33]:
# EVALUATION
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features,batch_labels in test_loader:
      batch_features = batch_features.type(torch.float32)
      y_pred = model(batch_features)
      y_pred = (y_pred > 0.8).float() # CONVERSION OF PROB TO BIANRY PREDICTION
      batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
      accuracy_list.append(batch_accuracy)
# CALCULATING OVERALL ACCURACY
overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'OVERALL ACCURACY:{overall_accuracy:.4f}')

OVERALL ACCURACY:0.9080
