<a href="https://colab.research.google.com/github/JEN12H/PYTORCH/blob/main/TENSORS_PYTORCH.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("GPU IS AVAILABLE")
  print(f"Using gpu:{torch.cuda.get_device_name(0)}")
else:
  print("GPU IS NOT AVAILABLE")

GPU IS AVAILABLE
Using gpu:Tesla T4


# CREATING TENSORS


In [ ]:
a = torch.empty(2,3)
type(a)

torch.Tensor

In [ ]:
b = torch.zeros(2,4)
b

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
c = torch.ones(5,4)
c

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
torch.rand(3,4)

tensor([[0.0037, 0.0862, 0.4204, 0.2181],
        [0.4280, 0.5678, 0.2037, 0.6384],
        [0.6277, 0.5248, 0.2616, 0.2904]])

In [ ]:
torch.manual_seed(100) # BY USING SEED FUNCTION THE OUTPUT OF RAND FUNCTION REMAINS SAME FOR EVERY ONE WHO IS RUNNING THE NOTEBOOK
torch.rand(3,4)

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428],
        [0.2080, 0.1180, 0.1217, 0.7356]])

In [ ]:
torch.tensor([[2,3,4],[5,6,7]])

tensor([[2, 3, 4],
        [5, 6, 7]])

In [ ]:
# OTHER WAYS
print("USING ARANGE",torch.arange(0,10))
print("JUMPS",torch.arange(0,10,2))
print("USING LINSPACE",torch.linspace(0,10,10))
print("USNIG EYE",torch.eye(5)) # IDENTITY MATRIX
print("USING FULL",torch.full((3,3),5)) # MATRIX OF SHAPE 3X3 WITH EVERY ITEM CONSISTING OF 5

USING ARANGE tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
JUMPS tensor([0, 2, 4, 6, 8])
USING LINSAPCE tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
USNIG EYE tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
USing FULL tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#SHAPES

In [ ]:
x = torch.tensor([[2,3,4],[10,11,12]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) # CREATE A NEW TENSOR WITH SAME SHAPE AS THAT OF x

tensor([[135315512511872,       190475520,               0],
        [              0,               0,               0]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

# DATA TYPES

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,10.0,12.0],dtype = torch.int32)

tensor([ 1, 10, 12], dtype=torch.int32)

In [ ]:
torch.tensor([1,10,12],dtype = torch.float32)

tensor([ 1., 10., 12.])

In [ ]:
x.to(torch.float64)

tensor([[ 2.,  3.,  4.],
        [10., 11., 12.]], dtype=torch.float64)

In [ ]:
torch.rand_like(x,dtype = torch.float64)

tensor([[0.6941, 0.3464, 0.9751],
        [0.7911, 0.4274, 0.4460]], dtype=torch.float64)

#OPERATIONS

In [ ]:
x+2

tensor([[ 4,  5,  6],
        [12, 13, 14]])

In [ ]:
x-1

tensor([[ 1,  2,  3],
        [ 9, 10, 11]])

In [ ]:
x*10

tensor([[ 20,  30,  40],
        [100, 110, 120]])

In [ ]:
x // 5

tensor([[0, 0, 0],
        [2, 2, 2]])

In [ ]:
x % 3

tensor([[2, 0, 1],
        [1, 2, 0]])

In [ ]:
x ** 3

tensor([[   8,   27,   64],
        [1000, 1331, 1728]])

In [ ]:
a = torch.empty(2,3)
b = torch.empty(2,3)
print("ADDITON",a+b)
print("SUBTRACTION",a-b)
print("MULTIPLICATION",a*b)
print("DIVISION",a/b)
print("EXPONENTIAL",a**b)

ADDITON tensor([[-7.3569e-24,  4.4148e-41,  2.2987e-31],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])
SUBTRACTION tensor([[ 7.3569e-24, -4.4148e-41,  2.1932e-33],
        [ 0.0000e+00, -4.4842e-44,  0.0000e+00]])
MULTIPLICATION tensor([[-0., 0., 0.],
        [0., 0., 0.]])
DIVISION tensor([[-2.2918e-08,  0.0000e+00,  1.0193e+00],
        [        nan,  0.0000e+00,         nan]])
EXPONENTIAL tensor([[1., 0., 1.],
        [1., 0., 1.]])


In [ ]:
torch.absolute(b)

tensor([[7.3569e-24, 4.4148e-41, 1.1384e-31],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [ ]:
torch.neg(x)

tensor([[ -2,  -3,  -4],
        [-10, -11, -12]])

In [ ]:
y = torch.tensor([1.4,2.6,3.9])
y

tensor([1.4000, 2.0000, 6.0000, 3.9000])

In [ ]:
torch.round(y)

tensor([1., 2., 6., 4.])

In [ ]:
torch.ceil(y)

tensor([2., 2., 6., 4.])

In [ ]:
torch.floor(y)

tensor([1., 2., 6., 3.])

In [ ]:
torch.clamp(y , min = 1,max=  5)

tensor([1.4000, 2.0000, 5.0000, 3.9000])

In [ ]:
e = torch.randint(size=(2,3),low =0, high = 10,dtype = torch.float32)
e

tensor([[3., 9., 4.],
        [0., 5., 7.]])

In [ ]:
torch.sum(e)

tensor(28)

In [ ]:
torch.sum(e, dim = 0) # ALONG COLUMNS

tensor([16,  5,  7])

In [ ]:
torch.sum(e,dim =1) # ALONG ROWS

tensor([ 7, 21])

In [ ]:
torch.mean(e)
torch.mean(e,dim=0)

tensor([1.5000, 7.0000, 5.5000])

In [ ]:
torch.median(e)

tensor(4.)

In [ ]:
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
torch.prod(e)

tensor(0.)

In [ ]:
torch.std(e)

tensor(3.1411)

In [ ]:
torch.var(e)

tensor(9.8667)

In [ ]:
torch.argmax(e)

tensor(1)

In [ ]:
torch.argmax(e)

tensor(1)

In [ ]:
f = torch.randint(size=(2,3),low =0, high = 10)
g = torch.randint(size=(3,2),low =0, high = 10)
print(f)
print(g)

tensor([[0, 9, 8],
        [2, 1, 5]])
tensor([[0, 5],
        [8, 8],
        [0, 2]])


In [ ]:
torch.matmul(f,g)

tensor([[77, 18],
        [62, 12]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,2])
torch.dot(vector1,vector2)

tensor(7)

In [ ]:
torch.transpose(f,0,1)

tensor([[8, 5],
        [3, 0],
        [3, 6]])

In [ ]:
h = torch.randint(size=(3,3),low= 0,high= 10,dtype =torch.float32)
torch.inverse(h)

tensor([[ 0.2897, -0.0841,  0.0748],
        [ 0.1028, -0.1589,  0.2523],
        [-0.4486,  0.4206, -0.3738]])

In [ ]:
i = torch.randint(size=(3,3),low= 0,high= 10,dtype =torch.float32)
j = torch.randint(size=(3,3),low= 0,high= 10,dtype =torch.float32)
i> j
i<j
i = j
i!= j

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [ ]:
torch.log(h)

tensor([[1.6094,   -inf, 0.0000],
        [2.0794, 2.0794, 1.9459],
        [1.0986, 2.1972, 1.3863]])

In [ ]:
torch.exp(h)

tensor([[1.4841e+02, 1.0000e+00, 2.7183e+00],
        [2.9810e+03, 2.9810e+03, 1.0966e+03],
        [2.0086e+01, 8.1031e+03, 5.4598e+01]])

In [ ]:
torch.sqrt(h)

tensor([[2.2361, 0.0000, 1.0000],
        [2.8284, 2.8284, 2.6458],
        [1.7321, 3.0000, 2.0000]])

In [ ]:
torch.sigmoid(h)

tensor([[0.9933, 0.5000, 0.7311],
        [0.9997, 0.9997, 0.9991],
        [0.9526, 0.9999, 0.9820]])

In [ ]:
torch.softmax(h,dim=0)

tensor([[4.7123e-02, 9.0212e-05, 2.3556e-03],
        [9.4650e-01, 2.6892e-01, 9.5033e-01],
        [6.3775e-03, 7.3099e-01, 4.7314e-02]])

In [ ]:
torch.relu(h)

tensor([[5., 0., 1.],
        [8., 8., 7.],
        [3., 9., 4.]])

# INPLACE OPERATIONS

In [ ]:
n = torch.rand(2,3)
m = torch.rand(2,3)
print(m)
print(n)

tensor([[0.7636, 0.3939, 0.9621],
        [0.8082, 0.0872, 0.9851]])
tensor([[0.0606, 0.1996, 0.2086],
        [0.7613, 0.1082, 0.3229]])


In [ ]:
m.add_(n) # NOW THIS WILL STORE THE RESULT OF ADDITION OF m AND n IN M ITSELF

tensor([[0.8241, 0.5935, 1.1706],
        [1.5695, 0.1954, 1.3080]])

In [ ]:
m

tensor([[0.8241, 0.5935, 1.1706],
        [1.5695, 0.1954, 1.3080]])

In [ ]:
m.relu_()

tensor([[0.8241, 0.5935, 1.1706],
        [1.5695, 0.1954, 1.3080]])

# COPYING A TENSOR

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.4881, 0.7793, 0.0636],
        [0.3078, 0.8137, 0.3209]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.4881, 0.7793, 0.0636],
        [0.3078, 0.8137, 0.3209]])

In [ ]:
id(a)

136687566783408

In [ ]:
id(b)

136687566783408

In [ ]:
b = a.clone()

In [ ]:
a[0][0] = 10

b

tensor([[0.4881, 0.7793, 0.0636],
        [0.3078, 0.8137, 0.3209]])

In [ ]:
a

tensor([[10.0000,  0.7793,  0.0636],
        [ 0.3078,  0.8137,  0.3209]])

# TENSOR OPERATIONS ON GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda') # WE ARE STORING OUR GPU DEVICE

In [ ]:
# CREATING A TENSOR ON GPU
torch.rand((2,3),device=device)

tensor([[0.0349, 0.0942, 0.2379],
        [0.8754, 0.1150, 0.0041]], device='cuda:0')

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.6302, 0.0466, 0.5211],
        [0.2612, 0.5650, 0.1716]])

In [ ]:
b = a.to(device)

# RESHAPING TENSORS

In [ ]:
a = torch.ones(2,2)
a

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
a.reshape(1,2,2)

tensor([[[1., 1.],
         [1., 1.]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b
b.permute(2,0,1)

tensor([[[0.7743, 0.7569, 0.6700],
         [0.8623, 0.1992, 0.8520]],

        [[0.4677, 0.2021, 0.8940],
         [0.0698, 0.7819, 0.9083]],

        [[0.3130, 0.8072, 0.4749],
         [0.8544, 0.8186, 0.2266]],

        [[0.7943, 0.8855, 0.4707],
         [0.8038, 0.1980, 0.8591]]])

In [ ]:
#unsqueeze - adds a dimension
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
#squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

#NUMPY TO PYTORCH

In [ ]:
import numpy as np


In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])